travis:
  secure:
    BINSTAR_TOKEN: wgIRAjXwAcbi1P8FjrJ6arpxsQqYHJhgrJhR7//gv4owLIhD36/QRHNJm6dyH8s4KRpoHhGSHd+oj1EZI+Cwgdm34ROo5KO+DdRTUAX1qElNakBa4IO3kOBL5BeRVX3oyeBRFokyqHKcFTsoSuO2wFDCZoPpwn53OnRwOSXiyIQVvnd3b2X+amoB83OrphsU0Nh/8HmZjK2QIbZyyqaaGrnXHzoInjXf2TDoYFgz1bX6UvSb8iKvxbxjgdJuIfDGpbB88vWpf2e/f8gFKRo0x34o102MDJQHXCFhGMaPAdEHPE+OsKRdvTTkCIjz8NTBtcgRoPaQQOKtc/Uq5HsSEC25A9zGUJkZSXlA5OVxZLDnJYiPWuI0+QXwKkc7WINBzH/6R4ouaZdKkX6BdAYHi8OPMhBdt6CJ1lWUzFAt0oE4IlTA6qwWnvGaFJzovZfFfZXuhorDBezfbsizX/dZ1JWHXjrnQsXTGetvt0TPh2Aeg9spl3iaqdN/rycM1o2fS/6zK7qKo72JQt0sbenPggIZJewowEdmBDLsNZ1UrS9cXUVUJmat95LcJTJGkfq/s6fCf5BN/ity4+qb95cUME/jtIEULCt2hfUHK95ovYFsMRrgh0pJko7NgObcevlzl6H0MqesS+MjcM+AEOXZo6HhP4jfA6HWvYmMibfGgJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
