travis:
  secure:
    BINSTAR_TOKEN: ySsvMntnLUC3b2Cbqx3/v3KHpXczSudpLsSuKSz5++RimwvRUFZQ/2F+c44uQnaBIEXSsj2qeFn8CrZHWU/NUuJYtykn9aNw1n9LL2TRYmgyuDWge0uRjNiJDR0Bj4iLgySKVq0amoqVVdxjO3k/55LcQyypSqv8bgpTuttDqSuRKVUHP4hNqhFlrQMieOjvvNtsCkcsnfiV9QlycNCqvIRfuANcFmN3GpfEGUrOBpZe9q85sCi1lAZoa2yiBr5o8GRwdftryPfF6xbYz2rHfbKLgKifX/r4HtAcbdbosjY8Z2zgdbrOjNTcon6vKoUVrc99JVGQ6HEn+yder0QUlwTNOJIGHIIAVh2+I6YyeDpUW4Jr8AHUU6FA3zODL9w5xhB1IVYQ2eJW1fE1B7FO9qFc54DMjlwqBZ1eDV3KQct/fal8yVOcHgX4brypSaYfs+jLe4lgNL1sELPvi64gAcDsVZzQprc6vA8x/Bh6J9mbSABy9EeEpfID+W+a5M1cvGA3SWPcmjDtzcsl2VNjYNCA33R/avMZAcRSn0PgxW4Adt3VvAxD8F0b8GueAsMpWQMxUv8UiMbas6mcpR7ZTzR0gg9lSLj+TII6ZQwXbEyVpPBddCuindSoFgcvy/CzbLUEmAYbJnRu8kUn3Gb3V3UiacAZF3P9v5ma3ygyGSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
